// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxIl3SKGNFuyW5uTWmDck8jb5a7SuUSfc',
    appId: '1:511367515700:web:63c999a308401059d3c461',
    messagingSenderId: '511367515700',
    projectId: 'unilost-and-found-b6bb3',
    authDomain: 'unilost-and-found-b6bb3.firebaseapp.com',
    databaseURL: 'https://unilost-and-found-b6bb3-default-rtdb.firebaseio.com',
    storageBucket: 'unilost-and-found-b6bb3.firebasestorage.app',
    measurementId: 'G-L61RH6XJHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSq2XhV2v402Hxiagd_aR9zVfTbnT25fU',
    appId: '1:511367515700:android:7d93e1b3e0395613d3c461',
    messagingSenderId: '511367515700',
    projectId: 'unilost-and-found-b6bb3',
    databaseURL: 'https://unilost-and-found-b6bb3-default-rtdb.firebaseio.com',
    storageBucket: 'unilost-and-found-b6bb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlIm1qPI2eSpiqQhcW4Mybbh9g51oySwM',
    appId: '1:511367515700:ios:8df496df9a243a24d3c461',
    messagingSenderId: '511367515700',
    projectId: 'unilost-and-found-b6bb3',
    databaseURL: 'https://unilost-and-found-b6bb3-default-rtdb.firebaseio.com',
    storageBucket: 'unilost-and-found-b6bb3.firebasestorage.app',
    iosBundleId: 'cat.uab.unilostfound.uniLostFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxIl3SKGNFuyW5uTWmDck8jb5a7SuUSfc',
    appId: '1:511367515700:web:ab3a60ec811970a0d3c461',
    messagingSenderId: '511367515700',
    projectId: 'unilost-and-found-b6bb3',
    authDomain: 'unilost-and-found-b6bb3.firebaseapp.com',
    databaseURL: 'https://unilost-and-found-b6bb3-default-rtdb.firebaseio.com',
    storageBucket: 'unilost-and-found-b6bb3.firebasestorage.app',
    measurementId: 'G-55ZP9GLQ3L',
  );

}